# Generated by Django 3.0.9 on 2020-08-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipe_recipeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='originCountry',
            new_name='origin_country',
        ),
    ]
