# Generated by Django 3.0.9 on 2020-08-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recipeitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeItems',
        ),
    ]
